### ISSUE TITLE
Example documentation?

### ISSUE THREAD

**Issue by vallieres** [rtheunissen/guzzle-rate-limiter#1]
Hello,

I'm looking for example on implementing your rate limiter for Guzzle. Can you point me to a tutorial or simply put a hello world type of example in your reply?

Thanks!

**Comment by rtheunissen** [comment]
I've added a basic example to the readme. Let me know if there is anything that doesn't make sense.

**Comment by vallieres** [comment]
Thanks! I ended up poking around and got it to work, but this will help for sure others!

**Comment by nailk** [comment]
Probably `$allowance = (float) $requests / $seconds;` should be replaced with `(float) $seconds * 1000000 / $requests;`?

Also, is the rate limiter suitable for distributed scripts?

**Comment by jamestowers** [comment]
@rtheunissen what is `$rateLimitProvider` in your example? 

```
use Concat\Http\Middleware\RateLimiter;

$handlerStack->push(new RateLimiter($rateLimitProvider));
```

I'm guessing its an implementation of the `RateLimitProvider` class but I can't work out how to use it. 
Using the example, I'm doing this:

```
$rateLimitProvider = new Provider();
        
$handlerStack = HandlerStack::create( new CurlHandler() );
$handlerStack->push(new RateLimiter($rateLimitProvider));

$this->client = new Client([ 'handler' => $handlerStack ]);
```

but it isn't working so i'm sure thats not right...

**Comment by rtheunissen** [comment]
> I'm guessing its an implementation of the RateLimitProvider class

@jamestowers this is correct.

The example implementation in the readme of this repo should give you enough information to implement your rate limit provider. You have to calculate or determine what the rate limit is. Read through the readme and if you still have questions I'd be happy to answer them.

The concept is that by storing the time of the last request, you can determine what the 'allowance' is for the next. If the next request is attempted in a shorter time than the allowance that was set, it will wait the difference.

**Comment by vallieres** [comment]
Exactly. I used the included readme doc and code to create our own RateLimitProvider.
