### ISSUE TITLE
Example-Implementation of the RateLimitProvider is misleading

### ISSUE THREAD

**Issue by thasmo** [rtheunissen/guzzle-rate-limiter#5]
First of all - thanks for providing this middleware, really appreciate it! 👍

I've noticed, that the `delay` method actually [expects microseconds](https://github.com/rtheunissen/guzzle-rate-limiter/blob/master/src/RateLimiter.php#L172), but the example provider uses `microtime(true)` which does not return microseconds but the current UNIX timestamp in seconds as float (which includes microseconds precision).

There's also a comment `The time unit for this value should match the time unit used across this implementation.` in the provider example, which is confusing. It will work using microseconds only actually, because the `delay` method uses `usleep` which will sleep for the given amount of microseconds - providing seconds or milliseconds would delay just a fraction of the actual desired duration.

**Comment by rtheunissen** [comment]
You're absolutely right. I was under the impression that `microtime` returned the microseconds, ie. x1000 of what it actually returns. TIL. 

`The time unit for this value should match the time unit used across this implementation` refers to the fact that you can override `delay` and sleep however you want. As long as you use the same unit across your implementation, it should work as expected.

Will update the example to use `sleep` instead. Thanks 👍

**Comment by rtheunissen** [comment]
@thasmo see 5a275c0cc6f3004275c8a51cbcf02990f1d6cf89

**Comment by thasmo** [comment]
@rtheunissen Thanks! :)
