### ISSUE TITLE
Consider using Guzzles own delay request option

### ISSUE THREAD

**Issue by ncla** [rtheunissen/guzzle-rate-limiter#8]
Hello,

I was looking at the source code, and was wondering why this middleware does not utilize Guzzle's own `delay` request option that is available to be set within a middleware?

http://docs.guzzlephp.org/en/latest/request-options.html#delay-option
http://docs.guzzlephp.org/en/latest/handlers-and-middleware.html#creating-a-handler

**Comment by ncla** [comment]
It seems that it is also faster from my quick dirty testing, when using `CurlMultiHandler` and `each_limit` for Pool.

**Comment by rtheunissen** [comment]
Thanks for pointing this out, I'll use this as an excuse to update some other things too.

**Comment by rtheunissen** [comment]
@ncla I haven't worked with guzzle in a long time. How does the `delay` option work exactly? Would it be enough to set that option in the rate-limiter middleware, or should I *apply* an existing delay option? 

I noticed that one potentially tricky part is `setLastRequestTime` which assumes that "now" is when the request is made because this is currently *after* the manual `sleep` delay.

**Comment by ncla** [comment]
The way I tested it was just simply adding `$options['delay'] = $delay * 1000;` in `__invoke`. I didn't think much about `setLastRequestTime` as I was hard-coding delay value for testing purposes.

**Comment by ncla** [comment]
You could maybe just add the additional `$delay` to `microtime(true)` for `setLastRequestTime` but then you have to change the method I think.

**Comment by tevino** [comment]
@rtheunissen The actual `LastRequestTime` could be fetched by passing another callback as [on_stats](https://docs.guzzlephp.org/en/stable/request-options.html#on-stats).

**Comment by tevino** [comment]
@rtheunissen This is the change that I've been playing with: #10 
CC @ncla

**Comment by rtheunissen** [comment]
I'm all for it 👍

**Comment by rtheunissen** [comment]
This should now be functional on master, tagged as v3.0.0
