### ISSUE TITLE
Example Provider class method `setLastRequestTime` will never store it in cache due to missing TTL parameter

### ISSUE THREAD

**Issue by ncla** [rtheunissen/guzzle-rate-limiter#9]
Any one copy pasting the example and using it as is will encounter bug where nothing is ever stored and it won't get rate-limited at all. I find it odd that no warning gets thrown for missing 3rd parameter..

https://github.com/laravel/framework/issues/16474
https://laravel.com/docs/5.7/cache#storing-items-in-the-cache

**Comment by rtheunissen** [comment]
Fixed using `forever` instead of `put`, thank you.
